# .github/workflows/sync-iplist.yml
name: Sync Cloudflare IP-List to gist
on:
  schedule:
    - cron: "*/5 * * * *"          # run every 5 minutes
  workflow_dispatch:               # adds the “Run workflow” button

env:
  CF_ACCOUNT:  ${{ secrets.CF_ACCOUNT_ID }}   # ← created in repo Secrets
  CF_LIST:     ${{ secrets.CF_LIST_ID }}      # ← created in repo Secrets
  CF_TOKEN:    ${{ secrets.CF_TOKEN }}        # ← created in repo Secrets

  GIST_ID:     YOUR_32_CHARACTER_GIST_ID      # ← paste from browser URL
  GIST_FILE:   ips.txt                        # filename inside the gist
  GIST_TOKEN:  ${{ secrets.GIST_TOKEN }}      # ← PAT (Read & write gists)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1 ▸ pull the IPs from your Cloudflare list
      - name: Fetch list
        run: |
          curl -sS -H "Authorization: Bearer $CF_TOKEN" \
               "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT/rules/lists/$CF_LIST/items" \
            | jq -r '.result[].value' | sort -u > list.txt

          # abort if Cloudflare returned nothing
          if [ ! -s list.txt ]; then
            echo "Cloudflare list empty – skipping gist update"
            exit 0
          fi

      # 2 ▸ write those IPs into ips.txt inside the gist
      - name: Update gist
        run: |
          jq -n \
            --arg f "$GIST_FILE" \
            --arg c "$(tr '\n' '\\n' < list.txt)" \
            '{files:{($f):{content:$c}}}' > body.json

          curl -sS -XPATCH \
               -H "Authorization: token $GIST_TOKEN" \
               -H "Content-Type: application/json" \
               -d @body.json \
               "https://api.github.com/gists/$GIST_ID"
